DROP TABLE IF EXISTS pt_수업_정보;
DROP TABLE IF EXISTS 소모품;
DROP TABLE IF EXISTS 운동기구;
DROP TABLE IF EXISTS 유지비;
DROP TABLE IF EXISTS 출입관리;
DROP TABLE IF EXISTS 트레이너;
DROP TABLE IF EXISTS 회원결제정산;
DROP TABLE IF EXISTS 회원카드;