DROP TABLE IF EXISTS 출입관리;
DROP TABLE IF EXISTS 회원의_결제_및_정산_현황;
DROP TABLE IF EXISTS 유지비_항목;
DROP TABLE IF EXISTS 운동기구_항목;
DROP TABLE IF EXISTS 소모품_항목;
DROP TABLE IF EXISTS 트레이너_및_직원_항목;
DROP TABLE IF EXISTS 회원카드_항목;